package model;
// Generated 06/05/2018 22:57:21 by Hibernate Tools 4.3.1



/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private int idAluno;
     private Pessoa pessoa;
     private String curso;
     private float nota1;
     private float nota2;
     private float media;

    public Aluno() {
    }

    public Aluno(Pessoa pessoa, String curso, float nota1, float nota2, float media) {
       this.pessoa = pessoa;
       this.curso = curso;
       this.nota1 = nota1;
       this.nota2 = nota2;
       this.media = media;
    }
   
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public float getNota1() {
        return this.nota1;
    }
    
    public void setNota1(float nota1) {
        this.nota1 = nota1;
    }
    public float getNota2() {
        return this.nota2;
    }
    
    public void setNota2(float nota2) {
        this.nota2 = nota2;
    }
    public float getMedia() {
        return this.media;
    }
    
    public void setMedia(float media) {
        this.media = media;
    }




}


