/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Pessoa;
import org.hibernate.Session;
import dao.DAO;
import model.Aluno;
/**
 *
 * @author victor
 */
public class JFrmTelaPrincipal extends javax.swing.JFrame {
    private Pessoa p;
    private Aluno a;
    private IFrmCadPessoa fp;
    private IFrmAluno fa; 
    private Session sessao;
    /**
     * Creates new form JFrmTelaPrincipal
     */
    public JFrmTelaPrincipal() {
        initComponents();
        sessao = DAO.getSessionFactory().openSession();
        p = new Pessoa();
        fp = null;
        
        a = new Aluno();
        fa = null;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniCadPessoa = new javax.swing.JMenuItem();
        mniCadAluno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnExPessoa = new javax.swing.JMenuItem();
        mnExAluno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jMenu1.setText("Cadastro");

        mniCadPessoa.setText("Pessoa");
        mniCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(mniCadPessoa);

        mniCadAluno.setText("Aluno");
        mniCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(mniCadAluno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exibir");

        mnExPessoa.setText("Pessoa");
        jMenu2.add(mnExPessoa);

        mnExAluno.setText("Aluno");
        jMenu2.add(mnExAluno);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(941, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadPessoaActionPerformed
        
        p=new Pessoa();
        
        fp = new IFrmCadPessoa(p, this);
        jDesktopPrincipal.add(fp);
        fp.setVisible(true);
        

    }//GEN-LAST:event_mniCadPessoaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        sessao.getSessionFactory().close();
    }//GEN-LAST:event_formWindowClosed

    private void mniCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadAlunoActionPerformed
       
        a=new Aluno();
        
        fa = new IFrmAluno(a, this, p);
        jDesktopPrincipal.add(fa);
        fa.setVisible(true);
        
    }//GEN-LAST:event_mniCadAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnExAluno;
    private javax.swing.JMenuItem mnExPessoa;
    private javax.swing.JMenuItem mniCadAluno;
    private javax.swing.JMenuItem mniCadPessoa;
    // End of variables declaration//GEN-END:variables
}
